export const CITIES = {
  // === Easy ===
  sapporo: {
    name: "札幌", icon: "🏔️", difficulty: "easy",
    rent: 800, baseCustomers: 18,
    personas: { family: 40, student: 30, couple: 10, business: 10, gourmet: 10 },
    specialEffect: "冬に観光客急増（雪まつり）",
    fairPriceBase: 1100,
    specialEvents: ["snowFestival"],
  },
  sendai: {
    name: "仙台", icon: "🌾", difficulty: "easy",
    rent: 700, baseCustomers: 18,
    personas: { family: 25, student: 25, couple: 20, business: 15, gourmet: 15 },
    specialEffect: "口コミ効果1.5倍",
    fairPriceBase: 1000,
    reviewMultiplier: 1.5,
    specialEvents: [],
  },
  kanazawa: {
    name: "金沢", icon: "🏯", difficulty: "easy",
    rent: 650, baseCustomers: 15,
    personas: { family: 10, student: 15, couple: 35, business: 10, gourmet: 30 },
    specialEffect: "和風ピザが高評価",
    fairPriceBase: 1200,
    soyBonus: 1.3,
    specialEvents: [],
  },
  shonan: {
    name: "湘南", icon: "🌊", difficulty: "easy",
    rent: 600, baseCustomers: 12,
    personas: { family: 15, student: 30, couple: 40, business: 5, gourmet: 10 },
    specialEffect: "週末に客3倍、天気影響大",
    fairPriceBase: 1100,
    weekendMultiplier: 3.0,
    weatherSensitivity: 2.0,
    specialEvents: [],
  },

  // === Normal ===
  kyoto: {
    name: "京都", icon: "🎓", difficulty: "normal",
    rent: 1200, baseCustomers: 22,
    personas: { family: 10, student: 15, couple: 20, business: 10, gourmet: 25, tourist: 20 },
    specialEffect: "外国人観光客あり、ユニークさが評価",
    fairPriceBase: 1300,
    uniquenessBonus: 1.2,
    specialEvents: ["autumnLeaves"],
  },
  nagoya: {
    name: "名古屋", icon: "🏙️", difficulty: "normal",
    rent: 1100, baseCustomers: 20,
    personas: { family: 30, student: 15, couple: 15, business: 35, gourmet: 5 },
    specialEffect: "コスパ重視の土地柄",
    fairPriceBase: 1000,
    priceWeight: 1.5,
    specialEvents: [],
  },
  yokohama: {
    name: "横浜", icon: "🛍️", difficulty: "normal",
    rent: 1300, baseCustomers: 22,
    personas: { family: 30, student: 10, couple: 35, business: 10, gourmet: 15 },
    specialEffect: "内装/見た目評価2倍",
    fairPriceBase: 1300,
    visualWeight: 2.0,
    specialEvents: [],
  },
  hiroshima: {
    name: "広島", icon: "⚾", difficulty: "normal",
    rent: 1000, baseCustomers: 14,
    personas: { family: 25, student: 25, couple: 20, business: 15, gourmet: 15 },
    specialEffect: "カープ試合日に客5倍",
    fairPriceBase: 1100,
    specialEvents: ["carpGame", "carpChampion"],
  },

  // === Hard ===
  osaka: {
    name: "大阪", icon: "🌆", difficulty: "hard",
    rent: 1800, baseCustomers: 28,
    personas: { family: 20, student: 25, couple: 15, business: 20, gourmet: 20 },
    specialEffect: "「安くてうまい」文化、価格にシビア",
    fairPriceBase: 900,
    priceWeight: 2.0,
    specialEvents: [],
  },
  tokyo: {
    name: "東京", icon: "🗼", difficulty: "hard",
    rent: 2500, baseCustomers: 22,
    personas: { family: 5, student: 10, couple: 15, business: 30, gourmet: 40 },
    specialEffect: "品質最厳、ライバル初期からいる",
    fairPriceBase: 1500,
    qualityWeight: 1.5,
    initialRivals: true,
    specialEvents: ["michelinRumor"],
  },
  okinawa: {
    name: "沖縄", icon: "🏝️", difficulty: "hard",
    rent: 500, baseCustomers: 14,
    personas: { family: 15, student: 10, couple: 20, business: 5, gourmet: 10, tourist: 40 },
    specialEffect: "食材仕入れ1.3倍",
    fairPriceBase: 1200,
    ingredientMarkup: 1.3,
    specialEvents: [],
  },
  fukuoka: {
    name: "福岡", icon: "🚀", difficulty: "hard",
    rent: 1400, baseCustomers: 16,
    personas: { family: 15, student: 30, couple: 15, business: 25, gourmet: 15 },
    specialEffect: "アジア観光客、成長型",
    fairPriceBase: 1100,
    growthRate: 0.02,
    specialEvents: [],
  },
};

export const CITY_LIST = Object.entries(CITIES).map(([id, data]) => ({ id, ...data }));
