export const COOK = {
  doughVertices: 24,
  doughInitialRadius: 30,
  guideRadius: 85,
  stretchSpeed: 0.8,
  sauceTypes: {
    tomato:   { name: "トマト",      color: "#D4392B", icon: "🍅" },
    genovese: { name: "ジェノベーゼ", color: "#27AE60", icon: "🌿" },
    white:    { name: "ホワイト",     color: "#F0E8D0", icon: "🥛" },
    soy:      { name: "和風醤油",    color: "#7B3F00", icon: "🫘" },
  },
  cheeseTypes: {
    mozzarella:  { name: "モッツァレラ",  color: "#FFF9C4" },
    cheddar:     { name: "チェダー",      color: "#FFB74D" },
    gorgonzola:  { name: "ゴルゴンゾーラ", color: "#B0BEC5" },
  },
  cheeseW: 50, cheeseH: 38,
  toppings: {
    basil:    { name: "バジル",       size: 26, type: "emoji", emoji: "🌿", stockKey: null },
    salami:   { name: "サラミ",       size: 44, type: "css",   stockKey: "salami_log" },
    olive:    { name: "オリーブ",     size: 20, type: "emoji", emoji: "🫒", stockKey: "olive_jar" },
    mushroom: { name: "マッシュルーム", size: 28, type: "css",  stockKey: null },
    shrimp:   { name: "エビ",         size: 36, type: "emoji", emoji: "🦐", stockKey: "shrimp_pack" },
    tomato_s: { name: "プチトマト",   size: 22, type: "emoji", emoji: "🍅", stockKey: null },
    anchovy:  { name: "アンチョビ",   size: 30, sizeH: 12, type: "css",  stockKey: null },
    honey:    { name: "はちみつ",     size: 8,  type: "drizzle", emoji: "🍯", color: "#DAA520", stockKey: null },
  },
  ovenInitialTemp: 200,
  ovenDecayRate: 0.6,
  logTempBoost: 30,
  optimalLow: 280,
  optimalHigh: 370,
  maxTemp: 450,
  oilColor: "#6B8E23",
};
