export const PROMOTIONS = {
  flyer: {
    name: "チラシ配り", icon: "📄",
    cost: 3000, effort: "none",
    effectMin: 0.20, effectMax: 0.40,
    duration: 1,
    unlockLevel: 5,
    desc: "翌日来客+20〜40%",
  },
  sns: {
    name: "SNS投稿", icon: "📱",
    cost: 0, effort: "photo+text",
    effectBase: 0,
    duration: 0,
    unlockLevel: 5,
    desc: "フォロワー依存の蓄積型効果",
    isSpecial: true,
  },
  coupon: {
    name: "クーポン", icon: "🎟️",
    cost: 2000,
    effort: "none",
    effectMin: 0.30, effectMax: 0.50,
    priceReduction: 0.15,
    duration: 3,
    unlockLevel: 5,
    desc: "来客+30〜50%、客単価-15%",
  },
  gourmetAd: {
    name: "グルメサイト広告", icon: "🖥️",
    cost: 8000, effort: "none",
    effectMin: 0.40, effectMax: 0.80,
    targetPersona: "gourmet",
    duration: 5,
    unlockLevel: 7,
    desc: "グルメ客+40〜80%",
  },
  tasting: {
    name: "試食会", icon: "🎉",
    cost: 0, effort: "cook3",
    effectMin: 0.30, effectMax: 0.60,
    duration: 3,
    unlockLevel: 7,
    desc: "ピザ3枚作成、来客+30〜60%",
  },
  pointCard: {
    name: "ポイントカード", icon: "💳",
    cost: 10000, effort: "none",
    repeatBoostMin: 0.15, repeatBoostMax: 0.25,
    duration: -1,
    unlockLevel: 10,
    desc: "リピート率+15〜25%（永続）",
  },
};
